version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automated"
    # reviewers:
    #   - "your-github-username"
    # assignees:
    #   - "your-github-username"
    # ignore:
    #   - dependency-name: "example-package"
    #     versions: ["1.x"]
